name: SrEmpregos
main: br.com.blecaute.jobs.SrEmpregos
version: 1.3.1
description: plugin de empregos
depend: [Vault]
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI, Legendchat]
author: SrBlecaute
commands:
  emprego:
    aliases: [empregos, job, jobs, trabalho, trabalhos]
    description: comando para visualizar os empregos